name: 'retailiq'
version: '1.0.0'
config-version: 2

profile: 'retailiq'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retailiq:
    staging:
      +materialized: view
    marts:
      +materialized: table
